site_name: Hadoop文档
site_author: lqinc
site_url: https://lqinc.github.io/Hadoop

# Repository
repo_name: lqinc/Hadoop
repo_url: https://github.com/lqinc/Hadoop
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 lqinc'

# Configuration
theme:
  name: 'material'
  custom_dir: 'custom/'
  palette:
    primary: 'deep-purple'
    accent: 'deep-purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'import_contacts'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/lqinc'
    - type: 'quote-left'
      link: 'https://lqinc.github.io/Hadoop'
    - type: 'book'
      link: 'https://lqinc.github.io/Hadoop'
